services:

  grafana:
    image: "grafana/grafana:13.1.4"
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./config/grafana/provisioning:/etc/grafana/provisioning:ro"
    ports:
      - "127.0.0.1:5000:3000"
    restart: "unless-stopped"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

  victoria-metrics:
    image: "victoriametrics/victoria-metrics:v1.150.0"
    volumes:
      - "victoria-metrics-data:/victoria-metrics-data"
    restart: "unless-stopped"
    command:
      - "--retentionPeriod=100y"

  loki:
    image: "grafana/loki:3.7.6"
    volumes:
      - "loki-data:/loki"
    restart: "unless-stopped"
    command:
      - "-config.file=/etc/loki/local-config.yaml"

  otel-collector:
    image: "otel/opentelemetry-collector-contrib:0.159.0"
    volumes:
      - "./config/otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro"
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
    restart: "unless-stopped"

volumes:
  grafana-data: {}
  victoria-metrics-data: {}
  loki-data: {}
