[[inputs.amd_rocm_smi]]
  name_override = "rocm"
  # Only keep the relevant tags.
  taginclude = ["host", "name"]

# Rename the tag.
[[processors.rename]]
  namepass = ["rocm"]
  [[processors.rename.replace]]
    tag = "name"
    dest = "device"

# Convert the fields to a tag.
[[processors.unpivot]]
  namepass = ["rocm"]
  fieldinclude = ["memory_*", "utilization_*", "power_draw"]
  tag_key = "type"
  value_key = "value"

### Memory

# Rename the value field.
[[processors.rename]]
  namepass = ["rocm"]
  tagpass = { type = ["memory_*"] }
  [[processors.rename.replace]]
    field = "value"
    dest = "memory_bytes"

# Remove the "memory_" prefix from the tag values.
[[processors.strings]]
  namepass = ["rocm"]
  tagpass = { type = ["memory_*"] }
  [[processors.strings.trim_prefix]]
    tag = "type"
    prefix = "memory_"

### Utilization

# Rename the value field and the type tag.
[[processors.rename]]
  namepass = ["rocm"]
  tagpass = { type = ["utilization_*"] }
  [[processors.rename.replace]]
    field = "value"
    dest = "usage_percent"
  [[processors.rename.replace]]
    tag = "type"
    dest = "resource"

# Remove the "utilization_" prefix from the tag values.
[[processors.strings]]
  namepass = ["rocm"]
  tagpass = { resource = ["utilization_*"] }
  [[processors.strings.trim_prefix]]
    tag = "resource"
    prefix = "utilization_"

### Power

# Rename the value field.
[[processors.rename]]
  namepass = ["rocm"]
  tagpass = { type = ["power_draw"] }
  tagexclude = ["type"]
  [[processors.rename.replace]]
    field = "value"
    dest = "power_watts"
