[[inputs.cpu]]
  percpu = false
  tagexclude = ["cpu"]

# Convert the "usage_*" fields to a tag.
[[processors.unpivot]]
  namepass = ["cpu"]
  tag_key = "state"
  value_key = "usage_percent"

# Remove the "usage_" prefix from the tag values.
[[processors.strings]]
  namepass = ["cpu"]
  [[processors.strings.trim_prefix]]
    tag = "state"
    prefix = "usage_"
