[[inputs.disk]]
  mount_points = ["/", "/boot", "/boot/efi", "/data"]
  fieldinclude = ["free", "used", "total"]
  taginclude = ["host", "path"]

# Convert the fields to a tag.
[[processors.unpivot]]
  namepass = ["disk"]
  tag_key = "type"
  value_key = "space_bytes"
