[[inputs.diskio]]
  devices = ["nvme0n1", "nvme1n1", "sda"]
  device_tags = ["ID_MODEL"]
  taginclude = ["host", "name", "ID_MODEL"]
  fieldinclude = ["*_bytes"]

# Rename the name and model tags.
[[processors.rename]]
  namepass = ["diskio"]
  [[processors.rename.replace]]
    tag = "name"
    dest = "device"
  [[processors.rename.replace]]
    tag = "ID_MODEL"
    dest = "model"

# Mapping for model tag values.
[[processors.enum]]
  namepass = ["diskio"]
  [[processors.enum.mapping]]
    tags = ["model"]
    [processors.enum.mapping.value_mappings]
      "Samsung SSD 970 EVO 500GB" = "970evo"
      "WDS500G3X0C-00SJG0" = "sn750"
      "CT2000MX500SSD1" = "mx500"

# Convert the "*_bytes" fields to a tag.
[[processors.unpivot]]
  namepass = ["diskio"]
  fieldinclude = ["*_bytes"]
  tag_key = "type"
  value_key = "io_bytes_total"

# Remove the "_bytes" suffix from the tag values.
[[processors.strings]]
  namepass = ["diskio"]
  [[processors.strings.trim_suffix]]
    tag = "type"
    suffix = "_bytes"
