[[inputs.net]]
  interfaces = ["wlp7s0"]
  fieldinclude = ["bytes_*"]

# Convert the "bytes_*" fields to a tag.
[[processors.unpivot]]
  namepass = ["net"]
  tag_key = "type"
  value_key = "io_bytes_total"

# Remove the "bytes_" prefix from the tag values.
[[processors.strings]]
  namepass = ["net"]
  [[processors.strings.trim_prefix]]
    tag = "type"
    prefix = "bytes_"
