[[inputs.sensors]]
  fieldpass = ["fan_input", "temp_input"]
  # Drop invalid sensor readings.
  [inputs.sensors.tagdrop]
    "feature" = ["fan1", "fan3", "auxtin*", "pch_*"]

# Rename the fields.
[[processors.rename]]
  namepass = ["sensors"]
  [[processors.rename.replace]]
    field = "temp_input"
    dest = "temp_celsius"
  [[processors.rename.replace]]
    field = "fan_input"
    dest = "fan_rpm"

# Mapping for chip and feature tag values.
[[processors.enum]]
  namepass = ["sensors"]
  [[processors.enum.mapping]]
    tags = ["chip"]
    [processors.enum.mapping.value_mappings]
      "mt7921_phy0-pci-0700" = "wifi"
      "spd5118-i2c-2-51" = "mem0"
      "spd5118-i2c-2-53" = "mem1"
      "amdgpu-pci-0f00" = "gpu_igpu"
      "amdgpu-pci-0300" = "gpu_r9700"
      "k10temp-pci-00c3" = "cpu"
      "nvme-pci-0600" = "nvme_sn750"
      "nvme-pci-0c00" = "nvme_970evo"
      "r8169_0_800:00-mdio-0" = "eth"
      "nct6799-isa-0290" = "mobo"
  [[processors.enum.mapping]]
    tags = ["feature"]
    [processors.enum.mapping.value_mappings]
      "fan2" = "cpu"
      "fan4" = "cha1_bottom"
      "fan5" = "cha2_back"
      "fan7" = "cha3_top"

# Remove the "_temp" suffix from some tag values.
[[processors.strings]]
  namepass = ["sensors"]
  [[processors.strings.trim_suffix]]
    tag = "feature"
    suffix = "_temp"
