[[inputs.smart]]
  use_sudo = true
  attributes = true
  tagpass = { name = ["Data_Units_*", "Total_LBAs_Written"] }
  taginclude = ["host", "device", "model", "name"]
  fieldinclude = ["raw_value"]

# Rename the measurement, field, and tag.
[[processors.rename]]
  namepass = ["smart_attribute"]
  [[processors.rename.replace]]
    measurement = "smart_attribute"
    dest = "smart"
  [[processors.rename.replace]]
    field = "raw_value"
    dest = "io_bytes_total"
  [[processors.rename.replace]]
    tag = "name"
    dest = "type"

# Bytes = 512000 * data units.
[[processors.scale]]
  namepass = ["smart"]
  tagpass = { type = ["Data_Units_*"] }
  [[processors.scale.scaling]]
    fields = ["io_bytes_total"]
    factor = 512000.0

# Bytes = 512 * LBAs.
[[processors.scale]]
  namepass = ["smart"]
  tagpass = { type = ["Total_LBAs_Written"] }
  [[processors.scale.scaling]]
    fields = ["io_bytes_total"]
    factor = 512.0

# Mapping for model and type tag values.
[[processors.enum]]
  namepass = ["smart"]
  [[processors.enum.mapping]]
    tags = ["model"]
    [processors.enum.mapping.value_mappings]
      "Samsung SSD 970 EVO 500GB" = "970evo"
      "WDS500G3X0C-00SJG0" = "sn750"
      "CT2000MX500SSD1" = "mx500"
  [[processors.enum.mapping]]
    tags = ["type"]
    [processors.enum.mapping.value_mappings]
      "Data_Units_Read" = "read"
      "Data_Units_Written" = "written"
      "Total_LBAs_Written" = "written"
