[[inputs.turbostat]]
  use_sudo = true
  # Only keep the relevant tags.
  taginclude = ["host", "cpu"]

### Power

# When cpu == "-" convert the "*_power_watt" fields to a tag.
[[processors.unpivot]]
  namepass = ["turbostat"]
  tagpass = { cpu = ["-"] }
  tagexclude = ["cpu"]
  fieldinclude = ["*_power_watt"]
  tag_key = "resource"
  value_key = "power_watts"

# Remove the "_power_watt" suffix from the tag values.
[[processors.strings]]
  namepass = ["turbostat"]
  [[processors.strings.trim_suffix]]
    tag = "resource"
    suffix = "_power_watt"

### Frequency

# Otherwise (when the cpu tag has not been removed) only keep the frequency field.
[[processors.rename]]
  namepass = ["turbostat"]
  tagpass = { cpu = ["*"] }
  fieldinclude = ["average_frequency_mhz"]
  [[processors.rename.replace]]
    field = "average_frequency_mhz"
    dest = "frequency_mhz"
