[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.kernel]]

[[inputs.mem]]

[[inputs.processes]]

[[inputs.system]]

[[inputs.diskio]]
  devices = ["nvme0n1", "nvme1n1", "sda"]
  device_tags = ["ID_MODEL", "ID_SERIAL_SHORT", "ID_WWN"]

[[inputs.smart]]
  use_sudo = true
  attributes = true
  devices = ["/dev/nvme0", "/dev/nvme1", "/dev/sda"]
  namedrop = ["smart_device"]
  tagexclude = ["capacity", "device", "enabled", "fail", "flags"]

[[inputs.turbostat]]
  use_sudo = true

[[inputs.temp]]

[[inputs.net]]
  interfaces = ["wlp7s0"]

[[inputs.wireless]]

[[inputs.sensors]]
  remove_numbers = true

[[inputs.amd_rocm_smi]]

[[outputs.opentelemetry]]
