[[inputs.kernel]]

[[inputs.processes]]

[[inputs.diskio]]
  devices = ["nvme0n1", "nvme1n1", "sda"]
  device_tags = ["ID_MODEL", "ID_SERIAL_SHORT", "ID_WWN"]

[[inputs.net]]
  interfaces = ["wlp7s0"]

[[inputs.wireless]]

[[outputs.opentelemetry]]
