api:
  enabled: true

enrichment_tables:

  # Map from priority numbers to priority texts and severity numbers.
  # Reference: https://docs.rsyslog.com/doc/configuration/modules/omotel.html
  syslog_priority:
    type: file
    file:
      path: /etc/vector/enrichment/syslog_priority.csv
      encoding:
        type: csv
    schema:
      priority_number: integer
      priority_text: string
      severity_number: integer

  # Map from common severity texts to severity numbers.
  otel_severity:
    type: file
    file:
      path: /etc/vector/enrichment/otel_severity.csv
      encoding:
        type: csv
    schema:
      severity_text: string
      severity_number: integer

sources:

  journald:
    type: journald
    log_namespace: true

  docker:
    type: docker_logs
    log_namespace: true
    include_labels: ["com.docker.compose.project=observability"]

transforms:

  journald_std:
    type: remap
    inputs: [journald]
    file: /etc/vector/vrl/journald_std.vrl

  docker_std:
    type: remap
    inputs: [docker]
    file: /etc/vector/vrl/docker_std.vrl

  route:
    type: exclusive_route
    inputs: [journald_std, docker_std]
    routes:
      - name: vector
        condition: .scope == "vector.service"
      - name: loki
        condition: .scope == "loki"
      - name: grafana
        condition: .scope == "grafana"

  vector_parser:
    type: remap
    inputs: [route.vector]
    file: /etc/vector/vrl/vector_parser.vrl

  loki_parser:
    type: remap
    inputs: [route.loki]
    file: /etc/vector/vrl/loki_parser.vrl

  grafana_parser:
    type: remap
    inputs: [route.grafana]
    file: /etc/vector/vrl/grafana_parser.vrl

  otel_fmt:
    type: remap
    inputs: [route._unmatched, vector_parser, loki_parser, grafana_parser]
    file: /etc/vector/vrl/otel_fmt.vrl

sinks:
  otel:
    type: opentelemetry
    inputs: [otel_fmt]
    protocol:
      type: http
      uri: http://localhost:4318/v1/logs
      encoding:
        codec: otlp
